### ISSUE TITLE
Legend

### ISSUE THREAD

**Issue by Xplorer001** [ExploreEmbedded/oneMicro-ATmega32#1]
1.  Markings on Back to select MCU
2. "P" for port is understood, can we name it  without P. Like A1 A2 ?
3. Marking to denote additional functionality like PWM, Analog etc. The front side can have only symbols and back side can tell what the symbol indicates.  
4. Programming header can be name ISP

**Comment by sharanago** [comment]
1.Done
2.Space is there to write P
3.Done for PWM
4.Done
